"""add gradcam_image_path to cases

Revision ID: c52d64ab2c31
Revises: 10b0f9f96d50
Create Date: 2026-08-31 12:42:20.809301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52d64ab2c31'
down_revision = '10b0f9f96d50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('gradcam_image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'gradcam_image_path')
    # ### end Alembic commands ###
